apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: k8sprom-patch-
resources:
- deployment.yaml
- sa.yaml
images:
- name: ghcr.io/doodlescheduling/k8sprom-patch-controller
  newTag: v0.2.1
