apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prometheus-patch-
resources:
- deployment.yaml
- sa.yaml
images:
- name: ghcr.io/doodlescheduling/prometheus-patch-controller
  newTag: v0.2.2
