apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prometheuspatch-
resources:
- deployment.yaml
- sa.yaml
images:
- name: ghcr.io/doodlescheduling/prometheuspatch-controller
  newTag: v0.2.2
