# permissions for end users to edit patchrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-patchrules-editor-role
rules:
- apiGroups:
  - metrics.infra.doodle.com
  resources:
  - prometheus-patchrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metrics.infra.doodle.com
  resources:
  - prometheus-patchrules/status
  verbs:
  - get
