# permissions for end users to view patchrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheuspatch-rules-viewer-role
rules:
- apiGroups:
  - metrics.infra.doodle.com
  resources:
  - prometheuspatch-rules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metrics.infra.doodle.com
  resources:
  - prometheuspatch-rules/status
  verbs:
  - get
