# permissions for end users to view patchrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-patchrules-viewer-role
rules:
- apiGroups:
  - metrics.infra.doodle.com
  resources:
  - prometheus-patchrules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metrics.infra.doodle.com
  resources:
  - prometheus-patchrules/status
  verbs:
  - get
